import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Posts } from './posts.entity';
import { PostMeta } from './post-meta.entity';

const mocRegions = [
  {
    ID: 1,
    post_id: 41,
    meta_key: 'FromRegion',
    meta_id: 2944,
    meta_value: 'Москва',
    region_value: 'Московская область',
  },
  {
    ID: 2,
    post_id: 42,
    meta_key: 'FromRegion',
    meta_id: 2956,
    meta_value: 'Санкт-Петербург',
    region_value: 'Ленинградская область',
  },
  {
    ID: 3,
    post_id: 43,
    meta_key: 'FromRegion',
    meta_id: 2967,
    meta_value: 'Благовещенск',
    region_value: 'Амурская область',
  },
  {
    ID: 4,
    post_id: 44,
    meta_key: 'FromRegion',
    meta_id: 2981,
    meta_value: 'Архангельск',
    region_value: 'Архангельская область',
  },
  {
    ID: 5,
    post_id: 45,
    meta_key: 'FromRegion',
    meta_id: 2996,
    meta_value: 'Барнаул',
    region_value: 'Алтайский край',
  },
  {
    ID: 6,
    post_id: 46,
    meta_key: 'FromRegion',
    meta_id: 3011,
    meta_value: 'Астрахань',
    region_value: 'Астраханская область',
  },
  {
    ID: 7,
    post_id: 47,
    meta_key: 'FromRegion',
    meta_id: 3255,
    meta_value: 'Белгород',
    region_value: 'Белгородская область',
  },
  {
    ID: 8,
    post_id: 48,
    meta_key: 'FromRegion',
    meta_id: 3261,
    meta_value: 'Брянск',
    region_value: 'Брянская область',
  },
  {
    ID: 9,
    post_id: 49,
    meta_key: 'FromRegion',
    meta_id: 3267,
    meta_value: 'Владимир',
    region_value: 'Владимирская область',
  },
  {
    ID: 10,
    post_id: 50,
    meta_key: 'FromRegion',
    meta_id: 3273,
    meta_value: 'Волгоград',
    region_value: 'Волгоградская область',
  },
  {
    ID: 11,
    post_id: 51,
    meta_key: 'FromRegion',
    meta_id: 3279,
    meta_value: 'Вологда',
    region_value: 'Вологодская область',
  },
  {
    ID: 12,
    post_id: 52,
    meta_key: 'FromRegion',
    meta_id: 3285,
    meta_value: 'Воронеж',
    region_value: 'Воронежская область',
  },
  {
    ID: 13,
    post_id: 53,
    meta_key: 'FromRegion',
    meta_id: 3291,
    meta_value: 'Биробиджан',
    region_value: 'Еврейская автономная область',
  },
  {
    ID: 14,
    post_id: 54,
    meta_key: 'FromRegion',
    meta_id: 3297,
    meta_value: 'Чита',
    region_value: 'Забайкальский край',
  },
  {
    ID: 15,
    post_id: 55,
    meta_key: 'FromRegion',
    meta_id: 3303,
    meta_value: 'Иваново',
    region_value: 'Ивановская область',
  },
  {
    ID: 16,
    post_id: 56,
    meta_key: 'FromRegion',
    meta_id: 3309,
    meta_value: 'Иркутск',
    region_value: 'Иркутская область',
  },
  {
    ID: 17,
    post_id: 57,
    meta_key: 'FromRegion',
    meta_id: 3315,
    meta_value: 'Краснодар',
    region_value: 'Краснодарский край',
  },
  {
    ID: 18,
    post_id: 58,
    meta_key: 'FromRegion',
    meta_id: 3321,
    meta_value: 'Красноярск',
    region_value: 'Красноярский край',
  },
  {
    ID: 19,
    post_id: 59,
    meta_key: 'FromRegion',
    meta_id: 3327,
    meta_value: 'Калуга',
    region_value: 'Калужская область',
  },
  {
    ID: 20,
    post_id: 60,
    meta_key: 'FromRegion',
    meta_id: 3333,
    meta_value: 'Кемерово',
    region_value: 'Кемеровская область',
  },
  {
    ID: 21,
    post_id: 61,
    meta_key: 'FromRegion',
    meta_id: 3339,
    meta_value: 'Киров',
    region_value: 'Кировская область',
  },
  {
    ID: 22,
    post_id: 62,
    meta_key: 'FromRegion',
    meta_id: 3345,
    meta_value: 'Кострома',
    region_value: 'Костромская область',
  },
  {
    ID: 23,
    post_id: 63,
    meta_key: 'FromRegion',
    meta_id: 3351,
    meta_value: 'Курган',
    region_value: 'Курганская область',
  },
  {
    ID: 24,
    post_id: 64,
    meta_key: 'FromRegion',
    meta_id: 3357,
    meta_value: 'Курск',
    region_value: 'Курская область',
  },
  {
    ID: 25,
    post_id: 65,
    meta_key: 'FromRegion',
    meta_id: 3363,
    meta_value: 'Липецк',
    region_value: 'Липецкая область',
  },
  {
    ID: 26,
    post_id: 66,
    meta_key: 'FromRegion',
    meta_id: 3472,
    meta_value: 'Мурманск',
    region_value: 'Мурманская область',
  },
  {
    ID: 27,
    post_id: 67,
    meta_key: 'FromRegion',
    meta_id: 3478,
    meta_value: 'Нижний Новгород',
    region_value: 'Нижегородская область',
  },
  {
    ID: 28,
    post_id: 68,
    meta_key: 'FromRegion',
    meta_id: 3484,
    meta_value: 'Великий Новгород',
    region_value: 'Новгородская область',
  },
  {
    ID: 29,
    post_id: 69,
    meta_key: 'FromRegion',
    meta_id: 3490,
    meta_value: 'Новосибирск',
    region_value: 'Новосибирская область',
  },
  {
    ID: 30,
    post_id: 70,
    meta_key: 'FromRegion',
    meta_id: 3496,
    meta_value: 'Пенза',
    region_value: 'Пензенская область',
  },
  {
    ID: 31,
    post_id: 71,
    meta_key: 'FromRegion',
    meta_id: 3502,
    meta_value: 'Псков',
    region_value: 'Псковская область',
  },
  {
    ID: 32,
    post_id: 72,
    meta_key: 'FromRegion',
    meta_id: 3508,
    meta_value: 'Пермь',
    region_value: 'Пермский край',
  },
  {
    ID: 33,
    post_id: 73,
    meta_key: 'FromRegion',
    meta_id: 3514,
    meta_value: 'Владивосток',
    region_value: 'Приморский край',
  },
  {
    ID: 34,
    post_id: 74,
    meta_key: 'FromRegion',
    meta_id: 3520,
    meta_value: 'Омск',
    region_value: 'Омская область',
  },
  {
    ID: 35,
    post_id: 75,
    meta_key: 'FromRegion',
    meta_id: 3526,
    meta_value: 'Оренбург',
    region_value: 'Оренбургская область',
  },
  {
    ID: 36,
    post_id: 76,
    meta_key: 'FromRegion',
    meta_id: 3532,
    meta_value: 'Орёл',
    region_value: 'Орловская область',
  },
  {
    ID: 37,
    post_id: 77,
    meta_key: 'FromRegion',
    meta_id: 3538,
    meta_value: 'Ростов',
    region_value: 'Ростовская область',
  },
  {
    ID: 38,
    post_id: 78,
    meta_key: 'FromRegion',
    meta_id: 3544,
    meta_value: 'Рязань',
    region_value: 'Рязанская область',
  },
  {
    ID: 39,
    post_id: 79,
    meta_key: 'FromRegion',
    meta_id: 3550,
    meta_value: 'Майкоп',
    region_value: null,
  },
  {
    ID: 40,
    post_id: 80,
    meta_key: 'FromRegion',
    meta_id: 3556,
    meta_value: 'Уфа',
    region_value: 'Республика Башкортостан',
  },
  {
    ID: 41,
    post_id: 81,
    meta_key: 'FromRegion',
    meta_id: 3562,
    meta_value: 'Улан-Удэ',
    region_value: 'Республика Бурятия',
  },
  {
    ID: 42,
    post_id: 82,
    meta_key: 'FromRegion',
    meta_id: 3568,
    meta_value: 'Элиста',
    region_value: 'Республика Калмыкия',
  },
  {
    ID: 43,
    post_id: 83,
    meta_key: 'FromRegion',
    meta_id: 3678,
    meta_value: 'Петрозаводск',
    region_value: 'Республика Карелия',
  },
  {
    ID: 44,
    post_id: 84,
    meta_key: 'FromRegion',
    meta_id: 3684,
    meta_value: 'Сыктывкар',
    region_value: 'Республика Коми',
  },
  {
    ID: 45,
    post_id: 85,
    meta_key: 'FromRegion',
    meta_id: 3690,
    meta_value: 'Новые территории',
    region_value: 'Республика Крым',
  },
  {
    ID: 46,
    post_id: 86,
    meta_key: 'FromRegion',
    meta_id: 3696,
    meta_value: 'Йошкар-Ола',
    region_value: 'Республика Марий Эл',
  },
  {
    ID: 47,
    post_id: 87,
    meta_key: 'FromRegion',
    meta_id: 3702,
    meta_value: 'Саранск',
    region_value: 'Республика Мордовия',
  },
  {
    ID: 48,
    post_id: 88,
    meta_key: 'FromRegion',
    meta_id: 3708,
    meta_value: 'Якутск',
    region_value: 'Республика Саха (Якутия)',
  },
  {
    ID: 49,
    post_id: 89,
    meta_key: 'FromRegion',
    meta_id: 3714,
    meta_value: 'Казань',
    region_value: 'Республика Татарстан',
  },
  {
    ID: 50,
    post_id: 90,
    meta_key: 'FromRegion',
    meta_id: 3720,
    meta_value: 'Кызыл',
    region_value: 'Республика Тыва',
  },
  {
    ID: 51,
    post_id: 91,
    meta_key: 'FromRegion',
    meta_id: 3726,
    meta_value: 'Южно-Сахалинск',
    region_value: 'Сахалинская область',
  },
  {
    ID: 52,
    post_id: 92,
    meta_key: 'FromRegion',
    meta_id: 3732,
    meta_value: 'Самара',
    region_value: 'Самарская область',
  },
  {
    ID: 53,
    post_id: 93,
    meta_key: 'FromRegion',
    meta_id: 3738,
    meta_value: 'Саратов',
    region_value: 'Саратовская область',
  },
  {
    ID: 54,
    post_id: 94,
    meta_key: 'FromRegion',
    meta_id: 3744,
    meta_value: 'Смоленск',
    region_value: 'Смоленская область',
  },
  {
    ID: 55,
    post_id: 95,
    meta_key: 'FromRegion',
    meta_id: 3750,
    meta_value: 'Екатеринбург',
    region_value: 'Свердловская область',
  },
  {
    ID: 56,
    post_id: 96,
    meta_key: 'FromRegion',
    meta_id: 3756,
    meta_value: 'Ставрополь',
    region_value: 'Ставропольский край',
  },
  {
    ID: 57,
    post_id: 97,
    meta_key: 'FromRegion',
    meta_id: 3762,
    meta_value: 'Тамбов',
    region_value: 'Тамбовская область',
  },
  {
    ID: 58,
    post_id: 98,
    meta_key: 'FromRegion',
    meta_id: 3768,
    meta_value: 'Томск',
    region_value: 'Томская область',
  },
  {
    ID: 59,
    post_id: 99,
    meta_key: 'FromRegion',
    meta_id: 3774,
    meta_value: 'Тверь',
    region_value: 'Тверская область',
  },
  {
    ID: 60,
    post_id: 100,
    meta_key: 'FromRegion',
    meta_id: 3885,
    meta_value: 'Тула',
    region_value: 'Тульская область',
  },
  {
    ID: 61,
    post_id: 101,
    meta_key: 'FromRegion',
    meta_id: 3891,
    meta_value: 'Тюмень',
    region_value: 'Тюменская область',
  },
  {
    ID: 62,
    post_id: 102,
    meta_key: 'FromRegion',
    meta_id: 3897,
    meta_value: 'Ульяновск',
    region_value: 'Ульяновская область',
  },
  {
    ID: 63,
    post_id: 103,
    meta_key: 'FromRegion',
    meta_id: 3903,
    meta_value: 'Ижевск',
    region_value: 'Удмуртская Республика',
  },
  {
    ID: 64,
    post_id: 104,
    meta_key: 'FromRegion',
    meta_id: 3909,
    meta_value: 'Хабаровск',
    region_value: 'Хабаровский край',
  },
  {
    ID: 65,
    post_id: 105,
    meta_key: 'FromRegion',
    meta_id: 3915,
    meta_value: 'Ханты-Мансийск',
    region_value: 'Ханты-Мансийский автономный округ',
  },
  {
    ID: 66,
    post_id: 106,
    meta_key: 'FromRegion',
    meta_id: 3921,
    meta_value: 'Челябинск',
    region_value: 'Челябинская область',
  },
  {
    ID: 67,
    post_id: 107,
    meta_key: 'FromRegion',
    meta_id: 3927,
    meta_value: 'Чебоксары',
    region_value: 'Чувашская Республика',
  },
  {
    ID: 68,
    post_id: 150658,
    meta_key: 'FromRegion',
    meta_id: 694772,
    meta_value: 'Новые территории',
    region_value: 'Республика Крым',
  },
  {
    ID: 69,
    post_id: 188788,
    meta_key: 'FromRegion',
    meta_id: 753336,
    meta_value: 'Ярославль',
    region_value: 'Ярославская область',
  },
];

@Injectable()
export class RegionsService {
  constructor(
    @InjectRepository(Posts)
    private postsRepository: Repository<Posts>,

    @InjectRepository(PostMeta)
    private postMetaRepository: Repository<PostMeta>,
  ) {}

  async getRegions(): Promise<any> {
    return mocRegions;
  }

  getPosts(): Promise<Posts[]> {
    return this.postsRepository.find({
      where: {
        ID: 41,
      },
    });
  }
}
